import { FormEvent, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Info } from 'lucide-react'
import { get, post, errorMessage, ApiError } from '../lib/api'
import { DirectoryUser } from '../lib/types'
import { Button, Field, Toggle, useToast } from '../components/ui'
import { useAuth } from '../main'

const initial = { service_name: '', description: '', service_type: 'INTERNAL', change_type: 'NEW', builder_id: '', developer_id: '', operator_id: '', department: '', reviewer_id: '', approver_id: '', planned_open_date: '', exposure: 'INTERNAL', has_admin_page: false, processes_personal_data: false, processes_credit_data: false, external_customer_service: false, uses_cloud: false, uses_docker: false, uses_kubernetes: false, external_integration: false, internet_access: false, business_criticality: 'MEDIUM', manual_rule_override_reason: '' }
export default function NewReview() {
  const { user } = useAuth(); const navigate = useNavigate(); const toast = useToast()
  const [form, setForm] = useState(initial)
  const [users, setUsers] = useState<DirectoryUser[]>([])
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [busy, setBusy] = useState(false)
  useEffect(() => { get<DirectoryUser[]>('/api/v1/users/directory').then(list => { setUsers(list); setForm(v => ({ ...v, builder_id: user.id, developer_id: user.id, department: user.department })) }) }, [user])
  const set = <K extends keyof typeof form>(key: K, value: typeof form[K]) => setForm(v => ({ ...v, [key]: value }))
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setErrors({}); try { const out = await post<{ id: string; assigned_items: number }>('/api/v1/review-requests', form); toast.push(`${out.assigned_items}개 체크리스트 항목이 배정되었습니다.`); navigate(`/reviews/${out.id}`) } catch (e) { if (e instanceof ApiError && e.details) setErrors(e.details as Record<string, string>); toast.push(errorMessage(e), 'error') } finally { setBusy(false) } }
  const userOptions = <>{users.map(u => <option key={u.id} value={u.id}>{u.display_name} ({u.department || u.username})</option>)}</>
  return <div className="page"><div className="page-header"><div><h1 className="page-title">신규 보안성 심의 요청</h1><p className="page-description">서비스 특성을 정확히 입력하면 Rule Engine이 게시된 템플릿에서 항목을 스냅샷으로 배정합니다.</p></div><Button onClick={() => navigate(-1)}><ArrowLeft size={14} /> 돌아가기</Button></div>
    <form onSubmit={submit}><section className="card"><div className="card-header"><h2>서비스 기본정보</h2></div><div className="card-body"><div className="form-grid"><Field label="서비스명" required error={errors.service_name}><input className="input" value={form.service_name} onChange={e => set('service_name', e.target.value)} /></Field><Field label="담당 부서" required error={errors.department}><input className="input" value={form.department} onChange={e => set('department', e.target.value)} /></Field><Field label="서비스 설명" required error={errors.description} className="span-2"><textarea className="textarea" value={form.description} onChange={e => set('description', e.target.value)} /></Field><Field label="서비스 유형" required><select className="select" value={form.service_type} onChange={e => set('service_type', e.target.value)}><option value="INTERNAL">대내 서비스</option><option value="EXTERNAL">대외 서비스</option><option value="ADMIN">관리자 서비스</option><option value="BATCH">배치/백엔드</option></select></Field><Field label="신규·변경 구분" required><select className="select" value={form.change_type} onChange={e => set('change_type', e.target.value)}><option value="NEW">신규</option><option value="CHANGE">변경</option><option value="REVIEW">재심의</option></select></Field><Field label="구축 담당자" required><select className="select" value={form.builder_id} onChange={e => set('builder_id', e.target.value)}><option value="">선택</option>{userOptions}</select></Field><Field label="개발 담당자" required><select className="select" value={form.developer_id} onChange={e => set('developer_id', e.target.value)}><option value="">선택</option>{userOptions}</select></Field><Field label="운영 담당자"><select className="select" value={form.operator_id} onChange={e => set('operator_id', e.target.value)}><option value="">선택 안 함</option>{userOptions}</select></Field><Field label="오픈 예정일"><input type="date" className="input" value={form.planned_open_date} onChange={e => set('planned_open_date', e.target.value)} /></Field><Field label="대내·대외 여부" required><select className="select" value={form.exposure} onChange={e => set('exposure', e.target.value)}><option value="INTERNAL">대내</option><option value="EXTERNAL">대외</option><option value="BOTH">대내·대외</option></select></Field><Field label="업무 중요도"><select className="select" value={form.business_criticality} onChange={e => set('business_criticality', e.target.value)}><option value="LOW">낮음</option><option value="MEDIUM">보통</option><option value="HIGH">높음</option><option value="CRITICAL">핵심</option></select></Field></div></div></section>
      <section className="card" data-sx="sx-030"><div className="card-header"><h2>적용 조건</h2><span className="subtle"><Info size={13} /> 체크리스트 자동 배정 입력값</span></div><div className="card-body"><div className="grid two"><Toggle label="관리자 페이지 존재" value={form.has_admin_page} onChange={v => set('has_admin_page', v)} /><Toggle label="개인정보 처리" value={form.processes_personal_data} onChange={v => set('processes_personal_data', v)} /><Toggle label="개인신용정보 처리" value={form.processes_credit_data} onChange={v => set('processes_credit_data', v)} /><Toggle label="외부 고객 서비스" value={form.external_customer_service} onChange={v => set('external_customer_service', v)} /><Toggle label="클라우드 사용" value={form.uses_cloud} onChange={v => set('uses_cloud', v)} /><Toggle label="Docker 사용" value={form.uses_docker} onChange={v => set('uses_docker', v)} /><Toggle label="Kubernetes 사용" value={form.uses_kubernetes} onChange={v => set('uses_kubernetes', v)} /><Toggle label="외부기관 연계" value={form.external_integration} onChange={v => set('external_integration', v)} /><Toggle label="인터넷 통신" value={form.internet_access} onChange={v => set('internet_access', v)} /></div></div></section>
      <div data-sx="sx-010"><Button variant="primary" disabled={busy}>{busy ? '생성 중…' : <>심의 생성 및 항목 배정 <ArrowRight size={15} /></>}</Button></div></form></div>
}
