import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Network, Plus, Save, Send, ShieldAlert, Trash2 } from 'lucide-react'
import { del, errorMessage, get, post, put } from '../lib/api'
import { Button, Field, LoadFailed, Loading, Toggle, formatDate, useToast } from '../components/ui'
import { useAuth } from '../main'

type Setting = { key: string; value: Record<string, unknown>; secret_configured: boolean; updated_at: string }
const tabs = [['general', '일반'], ['workflow', '검토·승인'], ['oidc', 'Keycloak OIDC'], ['upload', '파일 보안'], ['security', '접근 보안'], ['mail', '메일'], ['analytics', '방문 추적']]
export default function SettingsPage() {
  const toast = useToast(); const [settings, setSettings] = useState<Setting[]>(); const [tab, setTab] = useState('general'); const [draft, setDraft] = useState<Record<string, unknown>>({}); const current = useMemo(() => settings?.find(s => s.key === tab), [settings, tab]); const [failed, setFailed] = useState<unknown>(); const load = () => { setFailed(undefined); return get<Setting[]>('/api/v1/admin/settings').then(setSettings).catch(setFailed) }; useEffect(() => { load() }, []); useEffect(() => { setDraft({ ...(current?.value || {}) }) }, [current])
  const set = (key: string, value: unknown) => setDraft(v => ({ ...v, [key]: value })); const save = async () => { try { await put(`/api/v1/admin/settings/${tab}`, draft); toast.push('관리 설정을 저장했습니다.'); load() } catch (e) { toast.push(errorMessage(e), 'error') } }; const testOIDC = async () => { try { await post('/api/v1/admin/settings/oidc/test', { issuer: draft.issuer }); toast.push('OIDC Discovery 연결에 성공했습니다.') } catch (e) { toast.push(errorMessage(e), 'error') } }
  // The relay is asked for one real message with the saved settings, and
  // the answer -- and the attempt -- show up in the record underneath. The
  // address starts as the administrator's own but can be anything: an
  // administrator without a profile address used to get a 422 here, and a
  // relay that only accepts certain domains is found by trying one of them.
  const { user } = useAuth(); const [testRecipient, setTestRecipient] = useState(user.email || '')
  const testSMTP = async () => { try { const out = await post<{ sent_to: string }>('/api/v1/admin/settings/mail/test', { recipient: testRecipient.trim() }); toast.push(`${out.sent_to} 주소로 테스트 메일을 보냈습니다.`) } catch (e) { toast.push(errorMessage(e), 'error') } finally { loadDeliveries() } }
  // Saving a wrong clamd address used to be found by uploads that never
  // cleared, which blocks submission for whoever uploaded them.
  const testClamAV = async () => { try { const out = await post<{ address: string }>('/api/v1/admin/settings/upload/test', { address: String(draft.clamav_address || '') }); toast.push(`${out.address}의 clamd가 응답했습니다.`) } catch (e) { toast.push(errorMessage(e), 'error') } }
  // Each tab holds its own draft, so leaving one with pending edits used to
  // discard them without a word.
  const dirty = useMemo(() => Boolean(current) && JSON.stringify(draft) !== JSON.stringify({ ...current?.value }), [draft, current])
  useEffect(() => { if (!dirty) return; const warn = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = '' }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn) }, [dirty])
  const switchTab = (next: string) => { if (next === tab) return; if (dirty && !confirm('저장하지 않은 설정 변경이 있습니다. 이동하면 변경 내용이 사라집니다. 계속할까요?')) return; setTab(next) }
  const revert = () => setDraft({ ...(current?.value || {}) })
  // What the page policy refused since the process started. A snippet that
  // loads from an address the policy does not name is dropped by the browser
  // without a word; this is the only place an administrator can see that.
  const [violations, setViolations] = useState<Violation[]>(); const [violationsFailed, setViolationsFailed] = useState<unknown>()
  const loadViolations = () => { setViolationsFailed(undefined); return get<Violation[]>('/api/v1/admin/analytics/violations').then(setViolations).catch(setViolationsFailed) }
  useEffect(() => { if (tab === 'analytics') loadViolations() }, [tab])
  const allowOrigin = async (origin: string) => { try { await post('/api/v1/admin/analytics/allow', { origin }); toast.push(`${origin} 을(를) 허용 출처에 추가했습니다.`); load(); loadViolations() } catch (e) { toast.push(errorMessage(e), 'error') } }
  const clearViolations = async () => { try { await del('/api/v1/admin/analytics/violations'); loadViolations() } catch (e) { toast.push(errorMessage(e), 'error') } }
  // What left the building: every attempt the relay was asked to take,
  // with the subject and the recipient but never the body.
  const [deliveries, setDeliveries] = useState<DeliveryPage>(); const [deliveriesFailed, setDeliveriesFailed] = useState<unknown>()
  const loadDeliveries = () => { setDeliveriesFailed(undefined); return get<DeliveryPage>('/api/v1/admin/mail/deliveries?limit=50').then(setDeliveries).catch(setDeliveriesFailed) }
  useEffect(() => { if (tab === 'mail') loadDeliveries() }, [tab])
  if (failed) return <LoadFailed error={failed} onRetry={load} />
  if (!settings) return <Loading />
  return <div className="page"><div className="page-header"><div><h1 className="page-title">서비스 관리자 설정</h1><p className="page-description">환경변수 없이 운영 중 변경 가능하며 비밀값은 ENCRYPTION_KEY로 암호화됩니다.</p></div><div className="header-actions">{dirty && <span className="dirty-dot">저장하지 않은 변경</span>}{dirty && <Button onClick={revert}>되돌리기</Button>}<Button variant="primary" disabled={!dirty} onClick={save}><Save size={14} /> 설정 저장</Button></div></div><div className="tabs">{tabs.map(([key, label]) => <button key={key} className={`tab ${tab === key ? 'active' : ''}`} onClick={() => switchTab(key)}>{label}{dirty && tab === key ? ' •' : ''}</button>)}</div><div className="card"><div className="card-body">{tab === 'general' && <div className="form-grid"><Field label="서비스명"><input disabled className="input" value="SecCheck" /></Field><Field label="표시 시간대" help="IANA 이름. 화면·내보내기·요약 메일 시각이 모두 이 시간대로 표시됩니다."><input className="input" placeholder="Asia/Seoul" value={String(draft.timezone || '')} onChange={e => set('timezone', e.target.value)} /></Field><Field label="세션 시간(분)"><input type="number" className="input" value={Number(draft.session_minutes || 480)} onChange={e => set('session_minutes', Number(e.target.value))} /></Field><Field label="보존 기간(일)"><input type="number" className="input" value={Number(draft.retention_days || 1825)} onChange={e => set('retention_days', Number(e.target.value))} /></Field></div>}
      {tab === 'workflow' && <div className="grid two"><Toggle label="팀장/승인자 최종 승인 프로세스" value={Boolean(draft.approval_enabled)} onChange={v => set('approval_enabled', v)} /><div><Toggle label="본인이 신청한 심의를 본인이 검토·승인 허용" value={Boolean(draft.allow_self_review)} onChange={v => set('allow_self_review', v)} /><p className="subtle">기본은 금지입니다. 신청자와 검토자가 같은 사람이면 심의의 의미가 없기 때문이며, 담당자가 한 명뿐인 설치에서만 켜십시오.</p></div><Toggle label="검토자 배정 필수" value={Boolean(draft.require_reviewer_assignment)} onChange={v => set('require_reviewer_assignment', v)} /><div className="guide-block" data-sx="sx-021">승인 프로세스가 꺼져 있으면 보안 담당자의 검토 완료가 즉시 최종 심의 완료로 처리됩니다. 켜져 있으면 APPROVAL_PENDING 상태에서 승인자에게 전달됩니다.</div></div>}
      {tab === 'oidc' && <div className="form-grid"><div className="span-2"><Toggle label="Keycloak / OIDC SSO 활성화" value={Boolean(draft.enabled)} onChange={v => set('enabled', v)} /></div><Field label="Issuer URL" required={Boolean(draft.enabled)}><input className="input" placeholder="https://keycloak.example/realms/company" value={String(draft.issuer || '')} onChange={e => set('issuer', e.target.value)} /></Field><Field label="Client ID" required={Boolean(draft.enabled)}><input className="input" value={String(draft.client_id || '')} onChange={e => set('client_id', e.target.value)} /></Field><Field label="Client Secret" help={current?.secret_configured ? '암호화된 기존 비밀값이 설정되어 있습니다. 변경 시에만 입력하세요.' : 'Keycloak confidential client secret'}><input type="password" className="input" value={String(draft.client_secret || '')} onChange={e => set('client_secret', e.target.value)} /></Field><Field label="Callback URL" required={Boolean(draft.enabled)}><input className="input" placeholder="https://seccheck.example/api/v1/auth/oidc/callback" value={String(draft.redirect_url || '')} onChange={e => set('redirect_url', e.target.value)} /></Field><Field label="사용자명 Claim"><input className="input" value={String(draft.username_claim || 'preferred_username')} onChange={e => set('username_claim', e.target.value)} /></Field><Field label="신규 사용자 기본 역할" help="그룹 매핑에 해당하지 않는 사용자에게 부여됩니다."><select className="select" value={String(draft.default_role || 'REQUESTER')} onChange={e => set('default_role', e.target.value)}><option>REQUESTER</option><option>CONTRIBUTOR</option><option>AUDITOR</option></select></Field>
        <Field label="그룹 Claim" help="비우면 groups"><input className="input" placeholder="groups" value={String(draft.groups_claim || '')} onChange={e => set('groups_claim', e.target.value)} /></Field>
        <div className="span-2"><Toggle label="IdP 세션이 있으면 자동 로그인" value={Boolean(draft.auto_login)} onChange={v => set('auto_login', v)} /><p className="subtle">Keycloak 에 이미 로그인한 사람은 로그인 화면 없이 바로 들어옵니다(prompt=none). 세션이 없으면 로그인 화면이 한 번만 뜨고, 로그아웃한 뒤에는 자동으로 다시 로그인하지 않습니다.</p></div>
        <div className="span-2"><GroupMappings value={(draft.role_mappings as RoleMapping[]) || []} onChange={v => set('role_mappings', v)} /></div>
        <div className="span-2"><Button onClick={testOIDC}><Network size={14} /> Discovery 연결 테스트</Button></div></div>}
      {tab === 'upload' && <div className="form-grid"><Field label="최대 파일 크기(MB)"><input type="number" className="input" value={Number(draft.max_size_mb || 25)} onChange={e => set('max_size_mb', Number(e.target.value))} /></Field><Field label="허용 확장자" help="쉼표로 구분"><input className="input" value={Array.isArray(draft.allowed_extensions) ? draft.allowed_extensions.join(', ') : ''} onChange={e => set('allowed_extensions', e.target.value.split(',').map(x => x.trim()).filter(Boolean))} /></Field><div><Toggle label="ClamAV 악성코드 검사" value={Boolean(draft.clamav_enabled)} onChange={v => set('clamav_enabled', v)} /></div><Field label="ClamAV 주소" help="저장 전에 연결을 확인할 수 있습니다."><div className="search-box"><input className="input" placeholder="clamav:3310" value={String(draft.clamav_address || '')} onChange={e => set('clamav_address', e.target.value)} /><Button small onClick={testClamAV} disabled={!String(draft.clamav_address || '').trim()}>연결 테스트</Button></div></Field><Field label="삭제 증적 보관(일)" help="논리 삭제 후 이 기간이 지나면 암호문 파일을 볼륨에서 제거합니다. 메타데이터와 감사 기록은 남습니다."><input type="number" className="input" value={Number(draft.deleted_evidence_retention_days ?? 90)} onChange={e => set('deleted_evidence_retention_days', Number(e.target.value))} /></Field><div className="guide-block span-2">파일은 확장자와 실제 Magic/MIME을 함께 검증한 뒤 UUID 파일명으로 1MB 청크 AES-256-GCM 스트림으로 저장됩니다. 삭제된 증적의 암호문은 보관 기간이 지나면 매시간 유지보수 작업이 볼륨에서 제거하며, 파일명·해시·삭제자 기록은 감사 목적으로 보존됩니다.</div></div>}
      {tab === 'security' && <div className="form-grid"><div><Toggle label="HTTPS 전용 Secure Cookie" value={Boolean(draft.cookie_secure)} onChange={v => set('cookie_secure', v)} /></div>
        <div className="span-2"><Toggle label="/metrics를 인증 없이 공개" value={draft.metrics_public !== false} onChange={v => set('metrics_public', v)} /><p className="subtle">Prometheus 스크랩의 일반적인 방식입니다. 끄면 사용자 수, 24시간 로그인 실패 수, 잠긴 계정 수 같은 값이 공개되지 않으며, 읽기 범위 API 키로 계속 수집할 수 있습니다.</p></div><Field label="분당 요청 제한"><input type="number" className="input" value={Number(draft.rate_limit_per_minute || 120)} onChange={e => set('rate_limit_per_minute', Number(e.target.value))} /></Field><Field label="장기 미접속 관리자 잠금(일)"><input type="number" className="input" value={Number(draft.inactive_admin_lock_days || 90)} onChange={e => set('inactive_admin_lock_days', Number(e.target.value))} /></Field><Field label="분당 로그인 실패 제한" help="IP별 실패 시도만 계산합니다"><input type="number" className="input" value={Number(draft.login_rate_limit_per_minute ?? 30)} onChange={e => set('login_rate_limit_per_minute', Number(e.target.value))} /></Field><Field label="계정 잠금 실패 횟수" help="0이면 잠금을 사용하지 않습니다"><input type="number" className="input" value={Number(draft.max_login_failures ?? 5)} onChange={e => set('max_login_failures', Number(e.target.value))} /></Field><Field label="계정 잠금 시간(분)"><input type="number" className="input" value={Number(draft.lockout_minutes ?? 15)} onChange={e => set('lockout_minutes', Number(e.target.value))} /></Field><Field label="API 키 최대 유효기간(일)" help="0이면 제한 없음. 만료일을 비우고 발급하면 이 기간이 적용됩니다"><input type="number" className="input" value={Number(draft.api_key_max_days ?? 365)} onChange={e => set('api_key_max_days', Number(e.target.value))} /></Field><Field label="유휴 세션 만료(분)" help="0이면 세션 시간까지 유지"><input type="number" className="input" value={Number(draft.idle_timeout_minutes ?? 0)} onChange={e => set('idle_timeout_minutes', Number(e.target.value))} /></Field><div className="span-2"><Toggle label="관리자·검토자·승인자 계정에 일회용 코드(TOTP) 필수" value={Boolean(draft.require_totp_for_admins)} onChange={v => set('require_totp_for_admins', v)} /></div><Field label="신뢰 Reverse Proxy" className="span-2" help="쉼표로 구분한 IP 또는 CIDR. 설정하면 해당 Proxy의 X-Forwarded-For로 실제 클라이언트 IP를 판별합니다."><input className="input" value={Array.isArray(draft.trusted_proxies)?draft.trusted_proxies.join(', '):''} onChange={e=>set('trusted_proxies',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></Field><Field label="CORS 허용 Origin" className="span-2" help="쉼표로 구분, 예: https://itsm.example"><input className="input" value={Array.isArray(draft.cors_origins)?draft.cors_origins.join(', '):''} onChange={e=>set('cors_origins',e.target.value.split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean))}/></Field><div className="guide-block span-2">로그인 실패가 반복되면 계정이 자동으로 잠기며, 잠긴 계정은 사용자 및 역할 화면에서 해제할 수 있습니다. 만료된 세션과 보존 기간이 지난 로그는 매시간 자동으로 정리됩니다.</div></div>}
      {tab === 'mail' && <div className="form-grid"><div className="span-2"><Toggle label="메일 알림 활성화" value={Boolean(draft.enabled)} onChange={v => set('enabled', v)} /><p className="subtle">기본은 꺼짐. 켜면 인앱 알림 가운데 아래 스위치가 켜진 종류만 사내 SMTP 릴레이로 보냅니다. 인앱 알림은 항상 기록됩니다.</p></div><Field label="SMTP 호스트" required={Boolean(draft.enabled)} help="사내 릴레이 주소. 폐쇄망이면 postra 를 가리키십시오."><input className="input" placeholder="relay.company.internal" value={String(draft.smtp_host || '')} onChange={e => set('smtp_host', e.target.value)} /></Field><Field label="SMTP 포트" help="사내 릴레이는 대개 25"><input type="number" className="input" value={Number(draft.smtp_port || 25)} onChange={e => set('smtp_port', Number(e.target.value))} /></Field><Field label="전송 보안" help="auto 는 릴레이가 STARTTLS 를 알리면 쓰고 아니면 평문. 465 포트는 자동으로 tls."><select className="select" value={String(draft.security || 'auto')} onChange={e => set('security', e.target.value)}><option value="auto">auto (릴레이가 알리는 대로)</option><option value="none">none (평문, 내부망 전용)</option><option value="starttls">starttls (필수)</option><option value="tls">tls (Implicit TLS)</option></select></Field><div><Toggle label="TLS 인증서 검증 생략" value={Boolean(draft.skip_tls_verify)} onChange={v => set('skip_tls_verify', v)} /><p className="subtle">사내 인증서가 사설일 때만.</p></div><Field label="SMTP 사용자" help="인증 없는 릴레이가 흔하므로 선택 사항"><input className="input" value={String(draft.username || '')} onChange={e => set('username', e.target.value)} /></Field><Field label="SMTP 비밀번호" help={current?.secret_configured ? '설정됨 — 암호화되어 저장되어 있으며 다시 표시되지 않습니다. 바꿀 때만 입력하세요.' : '비워 두면 인증 없이 보냅니다.'}><input type="password" className="input" autoComplete="new-password" value={String(draft.password || '')} onChange={e => set('password', e.target.value)} /></Field><Field label="발신 주소" required={Boolean(draft.enabled)}><input className="input" placeholder="seccheck@company.internal" value={String(draft.from_address || '')} onChange={e => set('from_address', e.target.value)} /></Field><Field label="발신자 이름"><input className="input" value={String(draft.from_name || 'SecCheck')} onChange={e => set('from_name', e.target.value)} /></Field><Field label="서비스 주소" className="span-2" help="메일 속 바로가기 링크가 가리킬 이 서비스의 주소. 비워 두면 링크를 넣지 않습니다."><input className="input" placeholder="https://seccheck.company.internal" value={String(draft.base_url || '')} onChange={e => set('base_url', e.target.value)} /></Field><Field label="연결 제한 시간(초)"><input type="number" min={1} max={300} className="input" value={Number(draft.timeout_seconds || 10)} onChange={e => set('timeout_seconds', Number(e.target.value))} /></Field><Field label="일일 요약 발송 시각" help="0~23시. 요약 수신을 선택한 사용자에게 이 시각 이후 하루 한 번 발송합니다."><input type="number" min={0} max={23} className="input" value={Number(draft.digest_hour ?? 8)} onChange={e => set('digest_hour', Number(e.target.value))} /></Field>
        <div className="span-2"><h2 className="page-title" style={{ fontSize: 15 }}>보내는 이벤트</h2><p className="subtle">사람이 실제로 기다리는 일만 메일이 됩니다. 자기가 한 일은 자기에게 보내지 않고, 요약 수신자에게는 하루 한 통으로 묶습니다. 사용자는 알림 화면의 수신 설정에서 유형별로 더 끌 수 있습니다.</p></div>
        <div><Toggle label="내 차례" value={draft.notify_turn !== false} onChange={v => set('notify_turn', v)} /><p className="subtle">심의 제출·배정·인계, 항목 배정, 결재 요청, 보완 요청과 조치 완료, 후속조치 이행 보고</p></div><div><Toggle label="결과" value={draft.notify_decision !== false} onChange={v => set('notify_decision', v)} /><p className="subtle">심의 승인·반려·취소, 결재 요청 회수, 후속조치 이행 확인</p></div><div><Toggle label="기한" value={draft.notify_deadline !== false} onChange={v => set('notify_deadline', v)} /><p className="subtle">보완·후속조치 기한, 오픈 예정일, API 키 만료 임박, 심의 정체</p></div><div><Toggle label="장애" value={draft.notify_failure !== false} onChange={v => set('notify_failure', v)} /><p className="subtle">작업 큐 정체·재시도 소진, 저장 공간, 증적 무결성·악성코드, 감사로그 체인, 계정 잠금</p></div>
        <Field label="테스트 메일 받는 주소" className="span-2" help="저장한 설정으로 이 주소에 한 통을 보내고 결과를 아래 기록에 남깁니다. 기본은 내 프로필의 이메일 주소입니다."><div className="search-box"><input className="input" type="email" placeholder="admin@company.internal" value={testRecipient} onChange={e => setTestRecipient(e.target.value)} /><Button onClick={testSMTP} disabled={!testRecipient.trim()}><Send size={14} /> 테스트 메일 보내기</Button></div></Field>
        <div className="span-2"><div className="page-header"><div><h2 className="page-title" style={{ fontSize: 15 }}><Send size={14} /> 메일 발송 기록</h2><p className="subtle">릴레이에 넘긴 모든 시도입니다. 본문은 남기지 않습니다. {deliveries && <>성공 {deliveries.summary.SENT ?? 0} · 실패 {deliveries.summary.FAILED ?? 0} · 건너뜀 {deliveries.summary.SKIPPED ?? 0}</>}</p></div><div className="header-actions"><Button small onClick={loadDeliveries}>새로고침</Button></div></div>
          {deliveriesFailed ? <LoadFailed error={deliveriesFailed} onRetry={loadDeliveries} /> : !deliveries ? <Loading /> : deliveries.items.length === 0 ? <p className="subtle">아직 보낸 메일이 없습니다.</p> : <div className="table-wrap"><table><caption className="sr-only">메일 발송 기록</caption><thead><tr><th>시각</th><th>이벤트</th><th>수신자</th><th>제목</th><th>결과</th><th>오류</th></tr></thead>
            <tbody>{deliveries.items.map(d => <tr key={d.id}><td className="subtle">{formatDate(d.created_at, true)}</td><td><code>{d.event}</code></td><td>{d.recipient}</td><td>{d.subject}</td><td>{d.status === 'SENT' ? '성공' : d.status === 'FAILED' ? `실패 (${d.attempt}회)` : '건너뜀'}</td><td className="subtle">{d.error}</td></tr>)}</tbody></table></div>}</div></div>}
      {tab === 'analytics' && <div className="form-grid"><div className="span-2"><Toggle label="방문 추적 스크립트 삽입" value={Boolean(draft.enabled)} onChange={v => set('enabled', v)} /><p className="subtle">기본은 꺼짐입니다. 켜면 아래 도구의 스크립트가 화면에 삽입되고, 콘텐츠 보안 정책(CSP)에 요청마다 다른 nonce 와 그 도구의 출처가 더해집니다. 'unsafe-inline' 은 쓰지 않습니다.</p></div>
        <Field label="추적 도구" help="Momento 는 사내 수집기라 데이터가 밖으로 나가지 않습니다."><select className="select" value={String(draft.provider || 'none')} onChange={e => set('provider', e.target.value)}><option value="none">사용 안 함</option><option value="momento">Momento (사내)</option><option value="ga4">Google Analytics 4</option><option value="gtm">Google Tag Manager</option><option value="matomo">Matomo</option><option value="custom">직접 입력</option></select></Field>
        <Field label="삽입 위치" help="head 는 첫 화면부터, body 는 화면이 그려진 뒤에 읽힙니다."><select className="select" value={String(draft.placement || 'head')} onChange={e => set('placement', e.target.value)}><option value="head">head</option><option value="body">body</option></select></Field>
        {draft.provider === 'momento' && <><Field label="Momento 수집기 주소" required><input className="input" placeholder="https://momento.company.internal" value={String(draft.momento_url || '')} onChange={e => set('momento_url', e.target.value)} /></Field><Field label="Momento 사이트 ID" required><input className="input" placeholder="seccheck" value={String(draft.momento_site_id || '')} onChange={e => set('momento_site_id', e.target.value)} /></Field><div className="span-2"><Toggle label="같은 오리진 프록시(/momento/*)로 수집" value={draft.momento_proxy !== false} onChange={v => set('momento_proxy', v)} /><p className="subtle">켜 두면 브라우저는 이 서버의 /momento/ 경로로만 보내고 서버가 수집기로 넘깁니다. 정책에 외부 출처가 등장하지 않으므로 CSP 를 바꿀 수 없는 설치에서도 동작합니다.</p></div></>}
        {(draft.provider === 'ga4' || draft.provider === 'gtm') && <Field label={draft.provider === 'gtm' ? 'GTM 컨테이너 ID' : 'GA4 측정 ID'} required className="span-2"><input className="input" placeholder={draft.provider === 'gtm' ? 'GTM-XXXXXXX' : 'G-XXXXXXXXXX'} value={String(draft.measurement_id || '')} onChange={e => set('measurement_id', e.target.value)} /></Field>}
        {draft.provider === 'matomo' && <><Field label="Matomo 주소" required><input className="input" placeholder="https://matomo.company.internal" value={String(draft.matomo_url || '')} onChange={e => set('matomo_url', e.target.value)} /></Field><Field label="Matomo 사이트 ID" required><input className="input" value={String(draft.matomo_site_id || '')} onChange={e => set('matomo_site_id', e.target.value)} /></Field></>}
        {draft.provider === 'custom' && <Field label="직접 입력 추적 코드" required className="span-2" help="script 태그를 포함한 HTML. 8KB 까지. 코드 안의 http(s) 주소는 자동으로 정책 출처에 더해집니다."><textarea className="textarea" rows={6} maxLength={8192} value={String(draft.custom_snippet || '')} onChange={e => set('custom_snippet', e.target.value)} /></Field>}
        <Field label="추가 허용 출처" className="span-2" help="스니펫에서 읽어 내지 못한 출처. https://host 형식, 쉼표로 구분. 아래 차단 목록의 허용 버튼이 여기에 더합니다."><input className="input" placeholder="https://cdn.tracker.internal, https://collect.tracker.internal" value={String(draft.allowed_hosts || '')} onChange={e => set('allowed_hosts', e.target.value)} /></Field>
        <div className="span-2"><Toggle label="관리 화면에서도 추적" value={Boolean(draft.include_admin)} onChange={v => set('include_admin', v)} /><p className="subtle">기본은 아니오. 꺼져 있으면 /admin 으로 시작하는 화면으로 들어온 요청에는 스크립트를 넣지 않습니다.</p></div>
        <div className="span-2"><div className="page-header"><div><h2 className="page-title" style={{ fontSize: 15 }}><ShieldAlert size={14} /> 정책이 차단한 출처</h2><p className="subtle">추적이 켜진 동안 브라우저가 신고한 것입니다. 서버를 다시 시작하면 비워집니다.</p></div><div className="header-actions"><Button small onClick={loadViolations}>새로고침</Button><Button small onClick={clearViolations} disabled={!violations?.length}>목록 비우기</Button></div></div>
          {violationsFailed ? <LoadFailed error={violationsFailed} onRetry={loadViolations} /> : !violations ? <Loading /> : violations.length === 0 ? <p className="subtle">차단된 출처가 없습니다.</p> : <div className="table-wrap"><table><caption className="sr-only">콘텐츠 보안 정책이 차단한 출처</caption><thead><tr><th>출처</th><th>지시어</th><th>마지막 화면</th><th>횟수</th><th></th></tr></thead>
            <tbody>{violations.map(v => <tr key={`${v.directive} ${v.origin}`}><td><code>{v.origin}</code></td><td>{v.directive}</td><td className="subtle">{v.page}</td><td>{v.count}</td><td>{v.allowed ? <span className="subtle">허용됨</span> : <Button small onClick={() => allowOrigin(v.origin)}>허용</Button>}</td></tr>)}</tbody></table></div>}</div></div>}</div></div><p className="subtle"><CheckCircle2 size={13} /> 변경 사항은 감사로그에 기록됩니다.</p></div>
}

type RoleMapping = { group: string; role: string }
type Violation = { origin: string; directive: string; page: string; count: number; allowed: boolean }
type Delivery = { id: string; created_at: string; event: string; recipient: string; subject: string; status: string; attempt: number; error: string }
type DeliveryPage = { items: Delivery[]; summary: Record<string, number> }
const mappableRoles = ['REQUESTER', 'CONTRIBUTOR', 'SECURITY_REVIEWER', 'APPROVER', 'TEMPLATE_ADMIN', 'AUDITOR']

// Roles are re-read from the directory at every sign-in, so a mapping is also
// how access is taken away. System administrator is deliberately not offered.
function GroupMappings({ value, onChange }: { value: RoleMapping[]; onChange: (v: RoleMapping[]) => void }) {
  const edit = (i: number, patch: Partial<RoleMapping>) => onChange(value.map((row, n) => n === i ? { ...row, ...patch } : row))
  return <Field label="그룹 → 역할 매핑" help="지정하면 로그인할 때마다 IdP 그룹을 기준으로 역할을 다시 맞춥니다. 그룹에서 빠진 사용자는 해당 역할을 잃습니다. 비워 두면 기본 역할만 부여합니다. 시스템 관리자는 매핑할 수 없습니다.">
    <div>
      {value.map((row, i) => <div className="toggle-row" key={i}>
        <input className="input" placeholder="/security-reviewers" value={row.group} onChange={e => edit(i, { group: e.target.value })} />
        <select className="select" value={row.role} onChange={e => edit(i, { role: e.target.value })}>{mappableRoles.map(r => <option key={r}>{r}</option>)}</select>
        <Button small variant="danger" aria-label={`${row.group || '빈'} 그룹 매핑 삭제`} onClick={() => onChange(value.filter((_, n) => n !== i))}><Trash2 size={13} /></Button>
      </div>)}
      <Button small onClick={() => onChange([...value, { group: '', role: 'REQUESTER' }])}><Plus size={13} /> 매핑 추가</Button>
    </div>
  </Field>
}
