import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Network, Save } from 'lucide-react'
import { errorMessage, get, post, put } from '../lib/api'
import { Button, Field, Loading, Toggle, useToast } from '../components/ui'

type Setting = { key: string; value: Record<string, unknown>; secret_configured: boolean; updated_at: string }
const tabs = [['general', '일반'], ['workflow', '검토·승인'], ['oidc', 'Keycloak OIDC'], ['upload', '파일 보안'], ['security', '접근 보안'], ['notification', '알림']]
export default function SettingsPage() {
  const toast = useToast(); const [settings, setSettings] = useState<Setting[]>(); const [tab, setTab] = useState('general'); const [draft, setDraft] = useState<Record<string, unknown>>({}); const current = useMemo(() => settings?.find(s => s.key === tab), [settings, tab]); const load = () => get<Setting[]>('/api/v1/admin/settings').then(setSettings); useEffect(() => { load() }, []); useEffect(() => { setDraft({ ...(current?.value || {}) }) }, [current])
  const set = (key: string, value: unknown) => setDraft(v => ({ ...v, [key]: value })); const save = async () => { try { await put(`/api/v1/admin/settings/${tab}`, draft); toast.push('관리 설정을 저장했습니다.'); load() } catch (e) { toast.push(errorMessage(e), 'error') } }; const testOIDC = async () => { try { await post('/api/v1/admin/settings/oidc/test', { issuer: draft.issuer }); toast.push('OIDC Discovery 연결에 성공했습니다.') } catch (e) { toast.push(errorMessage(e), 'error') } }
  if (!settings) return <Loading />
  return <div className="page"><div className="page-header"><div><h1 className="page-title">서비스 관리자 설정</h1><p className="page-description">환경변수 없이 운영 중 변경 가능하며 비밀값은 ENCRYPTION_KEY로 암호화됩니다.</p></div><Button variant="primary" onClick={save}><Save size={14} /> 설정 저장</Button></div><div className="tabs">{tabs.map(([key, label]) => <button key={key} className={`tab ${tab === key ? 'active' : ''}`} onClick={() => setTab(key)}>{label}</button>)}</div><div className="card"><div className="card-body">{tab === 'general' && <div className="form-grid"><Field label="서비스명"><input disabled className="input" value="SecCheck" /></Field><Field label="표시 시간대"><input className="input" value={String(draft.timezone || '')} onChange={e => set('timezone', e.target.value)} /></Field><Field label="세션 시간(분)"><input type="number" className="input" value={Number(draft.session_minutes || 480)} onChange={e => set('session_minutes', Number(e.target.value))} /></Field><Field label="보존 기간(일)"><input type="number" className="input" value={Number(draft.retention_days || 1825)} onChange={e => set('retention_days', Number(e.target.value))} /></Field></div>}
      {tab === 'workflow' && <div className="grid two"><Toggle label="팀장/승인자 최종 승인 프로세스" value={Boolean(draft.approval_enabled)} onChange={v => set('approval_enabled', v)} /><Toggle label="검토자 배정 필수" value={Boolean(draft.require_reviewer_assignment)} onChange={v => set('require_reviewer_assignment', v)} /><div className="guide-block" data-sx="sx-021">승인 프로세스가 꺼져 있으면 보안 담당자의 검토 완료가 즉시 최종 심의 완료로 처리됩니다. 켜져 있으면 APPROVAL_PENDING 상태에서 승인자에게 전달됩니다.</div></div>}
      {tab === 'oidc' && <div className="form-grid"><div className="span-2"><Toggle label="Keycloak / OIDC SSO 활성화" value={Boolean(draft.enabled)} onChange={v => set('enabled', v)} /></div><Field label="Issuer URL" required={Boolean(draft.enabled)}><input className="input" placeholder="https://keycloak.example/realms/company" value={String(draft.issuer || '')} onChange={e => set('issuer', e.target.value)} /></Field><Field label="Client ID" required={Boolean(draft.enabled)}><input className="input" value={String(draft.client_id || '')} onChange={e => set('client_id', e.target.value)} /></Field><Field label="Client Secret" help={current?.secret_configured ? '암호화된 기존 비밀값이 설정되어 있습니다. 변경 시에만 입력하세요.' : 'Keycloak confidential client secret'}><input type="password" className="input" value={String(draft.client_secret || '')} onChange={e => set('client_secret', e.target.value)} /></Field><Field label="Callback URL" required={Boolean(draft.enabled)}><input className="input" placeholder="https://seccheck.example/api/v1/auth/oidc/callback" value={String(draft.redirect_url || '')} onChange={e => set('redirect_url', e.target.value)} /></Field><Field label="사용자명 Claim"><input className="input" value={String(draft.username_claim || 'preferred_username')} onChange={e => set('username_claim', e.target.value)} /></Field><Field label="신규 사용자 기본 역할"><select className="select" value={String(draft.default_role || 'REQUESTER')} onChange={e => set('default_role', e.target.value)}><option>REQUESTER</option><option>CONTRIBUTOR</option><option>AUDITOR</option></select></Field><div className="span-2"><Button onClick={testOIDC}><Network size={14} /> Discovery 연결 테스트</Button></div></div>}
      {tab === 'upload' && <div className="form-grid"><Field label="최대 파일 크기(MB)"><input type="number" className="input" value={Number(draft.max_size_mb || 25)} onChange={e => set('max_size_mb', Number(e.target.value))} /></Field><Field label="허용 확장자" help="쉼표로 구분"><input className="input" value={Array.isArray(draft.allowed_extensions) ? draft.allowed_extensions.join(', ') : ''} onChange={e => set('allowed_extensions', e.target.value.split(',').map(x => x.trim()).filter(Boolean))} /></Field><div><Toggle label="ClamAV 악성코드 검사" value={Boolean(draft.clamav_enabled)} onChange={v => set('clamav_enabled', v)} /></div><Field label="ClamAV 주소"><input className="input" placeholder="clamav:3310" value={String(draft.clamav_address || '')} onChange={e => set('clamav_address', e.target.value)} /></Field><div className="guide-block span-2">파일은 확장자와 실제 Magic/MIME을 함께 검증한 뒤 UUID 파일명으로 AES-256-GCM 암호화 저장됩니다.</div></div>}
      {tab === 'security' && <div className="form-grid"><div><Toggle label="HTTPS 전용 Secure Cookie" value={Boolean(draft.cookie_secure)} onChange={v => set('cookie_secure', v)} /></div><Field label="분당 요청 제한"><input type="number" className="input" value={Number(draft.rate_limit_per_minute || 120)} onChange={e => set('rate_limit_per_minute', Number(e.target.value))} /></Field><Field label="장기 미접속 관리자 잠금(일)"><input type="number" className="input" value={Number(draft.inactive_admin_lock_days || 90)} onChange={e => set('inactive_admin_lock_days', Number(e.target.value))} /></Field><Field label="분당 로그인 시도 제한" help="IP별 비밀번호 로그인 시도"><input type="number" className="input" value={Number(draft.login_rate_limit_per_minute ?? 10)} onChange={e => set('login_rate_limit_per_minute', Number(e.target.value))} /></Field><Field label="계정 잠금 실패 횟수" help="0이면 잠금을 사용하지 않습니다"><input type="number" className="input" value={Number(draft.max_login_failures ?? 5)} onChange={e => set('max_login_failures', Number(e.target.value))} /></Field><Field label="계정 잠금 시간(분)"><input type="number" className="input" value={Number(draft.lockout_minutes ?? 15)} onChange={e => set('lockout_minutes', Number(e.target.value))} /></Field><Field label="유휴 세션 만료(분)" help="0이면 세션 시간까지 유지"><input type="number" className="input" value={Number(draft.idle_timeout_minutes ?? 0)} onChange={e => set('idle_timeout_minutes', Number(e.target.value))} /></Field><Field label="신뢰 Reverse Proxy" className="span-2" help="쉼표로 구분한 IP 또는 CIDR. 설정하면 해당 Proxy의 X-Forwarded-For로 실제 클라이언트 IP를 판별합니다."><input className="input" value={Array.isArray(draft.trusted_proxies)?draft.trusted_proxies.join(', '):''} onChange={e=>set('trusted_proxies',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></Field><Field label="CORS 허용 Origin" className="span-2" help="쉼표로 구분, 예: https://itsm.example"><input className="input" value={Array.isArray(draft.cors_origins)?draft.cors_origins.join(', '):''} onChange={e=>set('cors_origins',e.target.value.split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean))}/></Field><div className="guide-block span-2">로그인 실패가 반복되면 계정이 자동으로 잠기며, 잠긴 계정은 사용자 및 역할 화면에서 해제할 수 있습니다. 만료된 세션과 보존 기간이 지난 로그는 매시간 자동으로 정리됩니다.</div></div>}
      {tab === 'notification' && <div className="form-grid"><div><Toggle label="이메일 알림 활성화" value={Boolean(draft.email_enabled)} onChange={v => set('email_enabled', v)} /></div><Field label="SMTP 호스트"><input className="input" value={String(draft.smtp_host || '')} onChange={e => set('smtp_host', e.target.value)} /></Field><Field label="SMTP 포트"><input type="number" className="input" value={Number(draft.smtp_port || 25)} onChange={e => set('smtp_port', Number(e.target.value))} /></Field><Field label="전송 보안"><select className="select" value={String(draft.smtp_tls_mode || 'starttls')} onChange={e=>set('smtp_tls_mode',e.target.value)}><option value="starttls">STARTTLS</option><option value="tls">Implicit TLS</option><option value="none">None (내부망 전용)</option></select></Field><Field label="SMTP 사용자"><input className="input" value={String(draft.smtp_username || '')} onChange={e=>set('smtp_username',e.target.value)} /></Field><Field label="SMTP 비밀번호" help={current?.secret_configured?'암호화된 비밀번호가 설정되어 있습니다. 변경 시에만 입력하세요.':''}><input type="password" className="input" value={String(draft.smtp_password || '')} onChange={e=>set('smtp_password',e.target.value)} /></Field><Field label="발신 주소"><input className="input" value={String(draft.from || '')} onChange={e => set('from', e.target.value)} /></Field><div className="guide-block span-2">이메일은 PostgreSQL 작업 큐에서 재시도되며, 실패 건수는 /metrics와 서버 로그에서 확인할 수 있습니다.</div></div>}</div></div><p className="subtle"><CheckCircle2 size={13} /> 변경 사항은 감사로그에 기록됩니다.</p></div>
}
