import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ChevronLeft, ChevronRight, Copy, FileSpreadsheet, Layers3, Plus, Search, Trash2 } from 'lucide-react'
import { del, errorMessage, get, post } from '../lib/api'
import { Page, Template } from '../lib/types'
import { Badge, Button, Empty, Field, Loading, Modal, StatusBadge, useToast } from '../components/ui'

export default function Templates() {
  const toast = useToast(); const [page, setPage] = useState<Page<Template>>(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', category: 'DEVELOPMENT', description: '', version: 'V1.0' })
  const [filter, setFilter] = useState({ q: '', category: '', active: '' }); const [offset, setOffset] = useState(0); const limit = 24
  const params = useMemo(() => { const qs = new URLSearchParams({ limit: String(limit), offset: String(offset) }); Object.entries(filter).forEach(([k, v]) => { if (v) qs.set(k, v) }); return qs }, [filter, offset])
  const load = () => get<Page<Template>>(`/api/v1/templates?${params}`).then(setPage)
  useEffect(() => { setPage(undefined); const timer = window.setTimeout(() => { load().catch(e => toast.push(errorMessage(e), 'error')) }, 180); return () => clearTimeout(timer) }, [params])
  const set = (key: keyof typeof filter, value: string) => { setOffset(0); setFilter(v => ({ ...v, [key]: value })) }
  const items = page?.items
  const create = async () => { try { const out = await post<{ id: string }>('/api/v1/templates', form); toast.push('템플릿 초안을 만들었습니다.'); setOpen(false); location.href = `/templates/${out.id}` } catch (e) { toast.push(errorMessage(e), 'error') } }
  const copy = async (item: Template) => { const name = prompt('복제할 템플릿 이름', `${item.name} 복사본`); if (!name) return; try { await post(`/api/v1/templates/${item.id}/copy`, { name }); toast.push('템플릿을 복제했습니다.'); load() } catch (e) { toast.push(errorMessage(e), 'error') } }
  // Only a draft that no review has snapshotted can be removed; the server
  // enforces the same rule, this just keeps the button off unusable cards.
  const removable = (item: Template) => !item.versions?.length || item.versions.every(v => v.status === 'DRAFT')
  const remove = async (item: Template) => { if (!confirm(`${item.name} 템플릿을 삭제할까요? 초안 버전과 항목이 함께 삭제됩니다.`)) return; try { await del(`/api/v1/templates/${item.id}`); toast.push('템플릿을 삭제했습니다.'); load() } catch (e) { toast.push(errorMessage(e), 'error') } }
  return <div className="page"><div className="page-header"><div><h1 className="page-title">체크리스트 템플릿</h1><p className="page-description">게시 버전은 직접 수정되지 않으며, 새 버전에서만 변경할 수 있습니다.</p></div><div className="header-actions"><Link to="/templates/import"><Button><FileSpreadsheet size={15} /> Excel 가져오기</Button></Link><Button variant="primary" onClick={() => setOpen(true)}><Plus size={15} /> 템플릿 생성</Button></div></div>
    <div className="toolbar"><div className="search-box"><Search /><input className="input" aria-label="템플릿 검색" placeholder="템플릿 이름, 설명, 분류 검색" value={filter.q} onChange={e => set('q', e.target.value)} /></div>
      <select className="select" aria-label="분류 필터" value={filter.category} onChange={e => set('category', e.target.value)}><option value="">전체 분류</option><option>DEVELOPMENT</option><option>PRIVACY</option><option>CLOUD</option><option>DOCKER</option><option>KUBERNETES</option></select>
      <select className="select" aria-label="사용 여부" value={filter.active} onChange={e => set('active', e.target.value)}><option value="">전체</option><option value="1">사용 중</option><option value="0">사용 중지</option></select>
      {page && <span className="subtle">{page.total}개 중 {page.total ? offset + 1 : 0}–{offset + page.items.length}</span>}</div>
    {!items ? <Loading /> : items.length ? <div className="grid three">{items.map(item => { const current = item.versions?.[0]; return <article className="card" key={item.id}><div className="card-body"><div data-sx="sx-011"><div className="stat-icon"><Layers3 size={20} /></div><Badge tone="blue">{item.category}</Badge></div><h3>{item.name}</h3><p className="subtle" data-sx="sx-042">{item.description || '설명이 없습니다.'}</p><div data-sx="sx-008">{current ? <><strong>{current.version}</strong><StatusBadge status={current.status} /><span className="subtle">총 {item.versions.length}개 버전</span></> : <Badge>버전 없음</Badge>}</div><div data-sx="sx-008">{item.active ? (item.published_version ? <span className="subtle">지금 배정: <strong>{item.published_version}</strong> · 항목 {item.published_items ?? 0}개</span> : <Badge tone="red">게시된 버전 없음 · 배정되지 않음</Badge>) : <Badge>사용 중지 · 배정되지 않음</Badge>}</div></div><div className="card-header" data-sx="sx-003"><Button small onClick={() => copy(item)}><Copy size={13} /> 복제</Button>{removable(item) && <Button small variant="danger" onClick={() => remove(item)}><Trash2 size={13} /> 삭제</Button>}<Link to={`/templates/${item.id}`}><Button small variant="primary">편집</Button></Link></div></article> })}</div> : <Empty title="조건에 맞는 템플릿이 없습니다." description="검색어를 바꾸거나 Excel 가져오기로 시작하세요." />}
    {page && (offset > 0 || page.has_more) && <div className="card"><div className="card-body pager"><span className="subtle">{page.total}개</span><div className="header-actions"><Button small disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - limit))}><ChevronLeft size={14} /> 이전</Button><Button small disabled={!page.has_more} onClick={() => setOffset(offset + limit)}>다음 <ChevronRight size={14} /></Button></div></div></div>}
    {open && <Modal title="체크리스트 템플릿 생성" onClose={() => setOpen(false)} footer={<><Button onClick={() => setOpen(false)}>취소</Button><Button variant="primary" disabled={!form.name} onClick={create}>생성</Button></>}><div className="form-grid"><Field label="템플릿 이름" required className="span-2"><input className="input" value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))} /></Field><Field label="분류"><select className="select" value={form.category} onChange={e => setForm(v => ({ ...v, category: e.target.value }))}><option>DEVELOPMENT</option><option>PRIVACY</option><option>CLOUD</option><option>DOCKER</option><option>KUBERNETES</option></select></Field><Field label="첫 버전"><input className="input" value={form.version} onChange={e => setForm(v => ({ ...v, version: e.target.value }))} /></Field><Field label="설명" className="span-2"><textarea className="textarea" value={form.description} onChange={e => setForm(v => ({ ...v, description: e.target.value }))} /></Field></div></Modal>}
  </div>
}
