import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Copy, FileSpreadsheet, Layers3, Plus } from 'lucide-react'
import { errorMessage, get, post } from '../lib/api'
import { Template } from '../lib/types'
import { Badge, Button, Empty, Field, Loading, Modal, StatusBadge, useToast } from '../components/ui'

export default function Templates() {
  const toast = useToast(); const [items, setItems] = useState<Template[]>(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', category: 'DEVELOPMENT', description: '', version: 'V1.0' })
  const load = () => get<Template[]>('/api/v1/templates').then(setItems); useEffect(() => { load() }, [])
  const create = async () => { try { const out = await post<{ id: string }>('/api/v1/templates', form); toast.push('템플릿 초안을 만들었습니다.'); setOpen(false); location.href = `/templates/${out.id}` } catch (e) { toast.push(errorMessage(e), 'error') } }
  const copy = async (item: Template) => { const name = prompt('복제할 템플릿 이름', `${item.name} 복사본`); if (!name) return; try { await post(`/api/v1/templates/${item.id}/copy`, { name }); toast.push('템플릿을 복제했습니다.'); load() } catch (e) { toast.push(errorMessage(e), 'error') } }
  return <div className="page"><div className="page-header"><div><h1 className="page-title">체크리스트 템플릿</h1><p className="page-description">게시 버전은 직접 수정되지 않으며, 새 버전에서만 변경할 수 있습니다.</p></div><div className="header-actions"><Link to="/templates/import"><Button><FileSpreadsheet size={15} /> Excel 가져오기</Button></Link><Button variant="primary" onClick={() => setOpen(true)}><Plus size={15} /> 템플릿 생성</Button></div></div>
    {!items ? <Loading /> : items.length ? <div className="grid three">{items.map(item => { const current = item.versions?.[0]; return <article className="card" key={item.id}><div className="card-body"><div style={{ display: 'flex', justifyContent: 'space-between' }}><div className="stat-icon"><Layers3 size={20} /></div><Badge tone="blue">{item.category}</Badge></div><h3>{item.name}</h3><p className="subtle" style={{ minHeight: 36 }}>{item.description || '설명이 없습니다.'}</p><div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>{current ? <><strong>{current.version}</strong><StatusBadge status={current.status} /><span className="subtle">총 {item.versions.length}개 버전</span></> : <Badge>버전 없음</Badge>}</div></div><div className="card-header" style={{ borderTop: '1px solid #edf0f4', borderBottom: 0 }}><Button small onClick={() => copy(item)}><Copy size={13} /> 복제</Button><Link to={`/templates/${item.id}`}><Button small variant="primary">편집</Button></Link></div></article> })}</div> : <Empty title="등록된 템플릿이 없습니다." description="Excel 가져오기 또는 신규 생성으로 시작하세요." />}
    {open && <Modal title="체크리스트 템플릿 생성" onClose={() => setOpen(false)} footer={<><Button onClick={() => setOpen(false)}>취소</Button><Button variant="primary" disabled={!form.name} onClick={create}>생성</Button></>}><div className="form-grid"><Field label="템플릿 이름" required className="span-2"><input className="input" value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))} /></Field><Field label="분류"><select className="select" value={form.category} onChange={e => setForm(v => ({ ...v, category: e.target.value }))}><option>DEVELOPMENT</option><option>PRIVACY</option><option>CLOUD</option><option>DOCKER</option><option>KUBERNETES</option></select></Field><Field label="첫 버전"><input className="input" value={form.version} onChange={e => setForm(v => ({ ...v, version: e.target.value }))} /></Field><Field label="설명" className="span-2"><textarea className="textarea" value={form.description} onChange={e => setForm(v => ({ ...v, description: e.target.value }))} /></Field></div></Modal>}
  </div>
}
