import { useEffect, useState } from 'react'
import { LockOpen, Plus, Shield, UserCheck, UserX } from 'lucide-react'
import { api, errorMessage, get, post, put } from '../lib/api'
import { User } from '../lib/types'
import { Badge, Button, Empty, Field, Loading, Modal, useToast } from '../components/ui'

const roleNames: Record<string, string> = { SYSTEM_ADMIN: '시스템 관리자', TEMPLATE_ADMIN: '체크리스트 관리자', SECURITY_REVIEWER: '보안 담당자', REQUESTER: '심의 요청자', CONTRIBUTOR: '공동 작성자', APPROVER: '승인자', AUDITOR: '감사자' }
export default function UsersPage() {
  const toast = useToast(); const [users, setUsers] = useState<User[]>(); const [create, setCreate] = useState(false); const [edit, setEdit] = useState<User>(); const load = () => get<User[]>('/api/v1/admin/users').then(setUsers); useEffect(() => { load() }, [])
  const active = async (user: User) => { try { await post(`/api/v1/admin/users/${user.id}/active`, { active: !user.active }); toast.push(user.active ? '계정을 비활성화했습니다.' : '계정을 활성화했습니다.'); load() } catch (e) { toast.push(errorMessage(e), 'error') } }
  const unlock = async (user: User) => { try { await post(`/api/v1/admin/users/${user.id}/unlock`); toast.push('로그인 잠금을 해제했습니다.'); load() } catch (e) { toast.push(errorMessage(e), 'error') } }
  return <div className="page"><div className="page-header"><div><h1 className="page-title">사용자 및 역할</h1><p className="page-description">RBAC 역할을 조합하고 비활성 계정의 세션을 즉시 종료하며, 로그인 실패로 잠긴 계정을 해제합니다.</p></div><Button variant="primary" onClick={() => setCreate(true)}><Plus size={15} /> 로컬 사용자</Button></div><div className="card">{!users ? <Loading /> : users.length ? <div className="table-wrap"><table><thead><tr><th>사용자</th><th>부서</th><th>인증</th><th>역할</th><th>상태</th><th></th></tr></thead><tbody>{users.map(u => <tr key={u.id}><td><strong>{u.display_name}</strong><div className="subtle">{u.username} · {u.email}</div></td><td>{u.department || '-'}</td><td><Badge tone={u.auth_source === 'oidc' ? 'blue' : ''}>{u.auth_source.toUpperCase()}</Badge></td><td>{u.roles.map(r => <Badge key={r} tone={r === 'SYSTEM_ADMIN' ? 'red' : 'purple'}>{roleNames[r] || r}</Badge>)}</td><td><Badge tone={u.active ? 'green' : 'red'}>{u.active ? '활성' : '비활성'}</Badge>{u.locked_until && <Badge tone="red">로그인 잠김</Badge>}</td><td><div data-sx="sx-007"><Button small onClick={() => setEdit(u)}><Shield size={13} /> 역할</Button>{u.locked_until && <Button small onClick={() => unlock(u)}><LockOpen size={13} /> 잠금 해제</Button>}<Button small variant={u.active ? 'danger' : ''} onClick={() => active(u)}>{u.active ? <UserX size={13} /> : <UserCheck size={13} />}</Button></div></td></tr>)}</tbody></table></div> : <Empty />}</div>{create && <CreateUser onClose={() => setCreate(false)} onSaved={load} />}{edit && <RoleModal user={edit} onClose={() => setEdit(undefined)} onSaved={load} />}</div>
}
function CreateUser({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const toast = useToast(); const [form, setForm] = useState({ username: '', display_name: '', email: '', department: '', password: '', roles: ['REQUESTER'] }); const submit = async () => { try { await post('/api/v1/admin/users', form); toast.push('로컬 사용자를 만들었습니다.'); onClose(); onSaved() } catch (e) { toast.push(errorMessage(e), 'error') } }; return <Modal title="로컬 사용자 생성" onClose={onClose} footer={<><Button onClick={onClose}>취소</Button><Button variant="primary" onClick={submit}>생성</Button></>}><div className="form-grid"><Field label="사용자명" required><input className="input" value={form.username} onChange={e => setForm(v => ({ ...v, username: e.target.value }))} /></Field><Field label="표시 이름" required><input className="input" value={form.display_name} onChange={e => setForm(v => ({ ...v, display_name: e.target.value }))} /></Field><Field label="이메일"><input className="input" value={form.email} onChange={e => setForm(v => ({ ...v, email: e.target.value }))} /></Field><Field label="부서"><input className="input" value={form.department} onChange={e => setForm(v => ({ ...v, department: e.target.value }))} /></Field><Field label="초기 비밀번호" required help="12자 이상"><input type="password" className="input" value={form.password} onChange={e => setForm(v => ({ ...v, password: e.target.value }))} /></Field><div className="span-2"><RoleChecks value={form.roles} onChange={roles => setForm(v => ({ ...v, roles }))} /></div></div></Modal> }
function RoleModal({ user, onClose, onSaved }: { user: User; onClose: () => void; onSaved: () => void }) { const toast = useToast(); const [roles, setRoles] = useState(user.roles); const save = async () => { try { await put(`/api/v1/admin/users/${user.id}/roles`, { roles }); toast.push('역할을 저장했습니다.'); onClose(); onSaved() } catch (e) { toast.push(errorMessage(e), 'error') } }; return <Modal title={`${user.display_name} 역할`} onClose={onClose} footer={<><Button onClick={onClose}>취소</Button><Button variant="primary" onClick={save}>저장</Button></>}><RoleChecks value={roles} onChange={setRoles} /></Modal> }
function RoleChecks({ value, onChange }: { value: string[]; onChange: (v: string[]) => void }) { return <div className="grid two">{Object.entries(roleNames).map(([code, name]) => <label className="toggle-row" key={code}><span><strong>{name}</strong><div className="subtle">{code}</div></span><input type="checkbox" checked={value.includes(code)} onChange={e => onChange(e.target.checked ? [...value, code] : value.filter(v => v !== code))} /></label>)}</div> }
